

python parallel_solver_wrapper.py\
 /home/liuwei/GAST/ACPP/AC/scenarios/lkh/instances_zql/initial.tsp\
 out.file 10 0 1234\
 -@1:LKH:solver /home/liuwei/GAST/ACPP/solvers/LKH-2.0.7/LKH\
 -@1:LKH:prefix -\
 -@1:ASCENT_CANDIDATES 50\
 -@1:BACKBONE_TRIALS 0\
 -@1:BACKTRACKING NO\
 -@1:CANDIDATE_SET_TYPE ALPHA\
 -@1:EXTRA_CANDIDATES 0\
 -@1:EXTRA_CANDIDATE_SET_TYPE QUADRANT\
 -@1:GAIN23 YES\
 -@1:GAIN_CRITERION YES\
 -@1:INITIAL_STEP_SIZE 1\
 -@1:INITIAL_TOUR_ALGORITHM WALK\
 -@1:INITIAL_TOUR_FRACTION 1\
 -@1:KICKS 1\
 -@1:KICK_TYPE 0\
 -@1:MAX_BREADTH 2147483647\
 -@1:MAX_CANDIDATES 5\
 -@1:MOVE_TYPE 5\
 -@1:PATCHING_A 1\
 -@1:PATCHING_C 0\
 -@1:POPULATION_SIZE 50\
 -@1:RESTRICTED_SEARCH YES\
 -@1:RUNS 1000\
 -@1:SUBGRADIENT YES\
 -@1:SUBSEQUENT_MOVE_TYPE 0\
 -@1:SUBSEQUENT_PATCHING YES
#-@1
#/home/liuwei/GAST/ACPP/solvers_liu/LKH-2.0.7/LKH\